# Generated by Django 5.2 on 2025-08-09 10:53

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[blog.validators.validate_title_no_bad_words],
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[blog.validators.validate_adult],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[blog.validators.validate_email_domain],
                verbose_name="email address",
            ),
        ),
    ]
